# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindowdual.ui'
#
# Created: Mon Nov 24 22:25:05 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindowDual(QtGui.QMainWindow):

    def __init__(self):
        super(Ui_MainWindowDual, self).__init__()

        self.setupUi(self)

    def setupUi(self, MainWindowDual):
        MainWindowDual.setObjectName("MainWindowDual")
        MainWindowDual.resize(1037, 629)
        self.centralwidget = QtGui.QWidget(MainWindowDual)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtGui.QSpacerItem(20, 383, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 132))
        font = QtGui.QFont()
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem1 = QtGui.QSpacerItem(693, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        spacerItem2 = QtGui.QSpacerItem(693, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButtonContatos_2 = QtGui.QPushButton(self.frame_2)
        self.pushButtonContatos_2.setMinimumSize(QtCore.QSize(191, 101))
        self.pushButtonContatos_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonContatos_2.setStyleSheet("background-image: url(:/Recursos/Imagens/avatar.png);")
        self.pushButtonContatos_2.setText("")
        self.pushButtonContatos_2.setObjectName("pushButtonContatos_2")
        self.horizontalLayout_2.addWidget(self.pushButtonContatos_2)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtGui.QSpacerItem(1178, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.pushButtonEncerrar = QtGui.QPushButton(self.centralwidget)
        self.pushButtonEncerrar.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButtonEncerrar.setObjectName("pushButtonEncerrar")
        self.horizontalLayout_3.addWidget(self.pushButtonEncerrar)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindowDual.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindowDual)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1037, 18))
        self.menubar.setObjectName("menubar")
        self.menuM_todos_para_DarumaFramework = QtGui.QMenu(self.menubar)
        self.menuM_todos_para_DarumaFramework.setObjectName("menuM_todos_para_DarumaFramework")
        self.menuM_todos_para_Registro_Registry = QtGui.QMenu(self.menubar)
        self.menuM_todos_para_Registro_Registry.setObjectName("menuM_todos_para_Registro_Registry")
        self.menuM_todo_regAguardarProcesso_DUAL_DarumaFramework = QtGui.QMenu(self.menuM_todos_para_Registro_Registry)
        self.menuM_todo_regAguardarProcesso_DUAL_DarumaFramework.setObjectName("menuM_todo_regAguardarProcesso_DUAL_DarumaFramework")
        self.menuM_todo_regEnterFinal_DUAL_DarumaFramework = QtGui.QMenu(self.menuM_todos_para_Registro_Registry)
        self.menuM_todo_regEnterFinal_DUAL_DarumaFramework.setObjectName("menuM_todo_regEnterFinal_DUAL_DarumaFramework")
        self.menuM_todo_regModoGaveta_DUAL_DarumaFramework = QtGui.QMenu(self.menuM_todos_para_Registro_Registry)
        self.menuM_todo_regModoGaveta_DUAL_DarumaFramework.setObjectName("menuM_todo_regModoGaveta_DUAL_DarumaFramework")
        self.menuM_todo_regTermica_DUAL_DarumaFramework = QtGui.QMenu(self.menuM_todos_para_Registro_Registry)
        self.menuM_todo_regTermica_DUAL_DarumaFramework.setObjectName("menuM_todo_regTermica_DUAL_DarumaFramework")
        self.menuM_todo_regCodePageAutomatico_DUAL_DarumaFramework = QtGui.QMenu(self.menuM_todos_para_Registro_Registry)
        self.menuM_todo_regCodePageAutomatico_DUAL_DarumaFramework.setObjectName("menuM_todo_regCodePageAutomatico_DUAL_DarumaFramework")
        self.menuM_todo_regZeroCortado_DUAL_DarumaFramework = QtGui.QMenu(self.menuM_todos_para_Registro_Registry)
        self.menuM_todo_regZeroCortado_DUAL_DarumaFramework.setObjectName("menuM_todo_regZeroCortado_DUAL_DarumaFramework")
        self.menuM_todos_para_Status_e_Testes = QtGui.QMenu(self.menubar)
        self.menuM_todos_para_Status_e_Testes.setObjectName("menuM_todos_para_Status_e_Testes")
        self.menuMenu_para_Testes = QtGui.QMenu(self.menuM_todos_para_Status_e_Testes)
        self.menuMenu_para_Testes.setObjectName("menuMenu_para_Testes")
        self.menuM_todos_para_Autentica_ao_e_Impress_o = QtGui.QMenu(self.menubar)
        self.menuM_todos_para_Autentica_ao_e_Impress_o.setObjectName("menuM_todos_para_Autentica_ao_e_Impress_o")
        self.menuExemplos = QtGui.QMenu(self.menubar)
        self.menuExemplos.setObjectName("menuExemplos")
        self.menuBobina_35_Colunas = QtGui.QMenu(self.menubar)
        self.menuBobina_35_Colunas.setObjectName("menuBobina_35_Colunas")
        MainWindowDual.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindowDual)
        self.statusbar.setObjectName("statusbar")
        MainWindowDual.setStatusBar(self.statusbar)
        self.actionM_todo_eDefinirProduto_Daruma = QtGui.QAction(MainWindowDual)
        self.actionM_todo_eDefinirProduto_Daruma.setObjectName("actionM_todo_eDefinirProduto_Daruma")
        self.actionM_todo_regRetornaValorChave_DarumaFramework = QtGui.QAction(MainWindowDual)
        self.actionM_todo_regRetornaValorChave_DarumaFramework.setObjectName("actionM_todo_regRetornaValorChave_DarumaFramework")
        self.actionM_todo_regLinhasGuilhotina_DUAL_DarumaFramework = QtGui.QAction(MainWindowDual)
        self.actionM_todo_regLinhasGuilhotina_DUAL_DarumaFramework.setObjectName("actionM_todo_regLinhasGuilhotina_DUAL_DarumaFramework")
        self.actionM_todo_regPortaComunicacao_DUAL_DarumaFramework = QtGui.QAction(MainWindowDual)
        self.actionM_todo_regPortaComunicacao_DUAL_DarumaFramework.setObjectName("actionM_todo_regPortaComunicacao_DUAL_DarumaFramework")
        self.actionM_todo_regTabulacao_DUAL_DarumaFramework = QtGui.QAction(MainWindowDual)
        self.actionM_todo_regTabulacao_DUAL_DarumaFramework.setObjectName("actionM_todo_regTabulacao_DUAL_DarumaFramework")
        self.actionM_todo_regVelocidade_DUAL_DarumaFramework = QtGui.QAction(MainWindowDual)
        self.actionM_todo_regVelocidade_DUAL_DarumaFramework.setObjectName("actionM_todo_regVelocidade_DUAL_DarumaFramework")
        self.action1_Habilitar = QtGui.QAction(MainWindowDual)
        self.action1_Habilitar.setObjectName("action1_Habilitar")
        self.actionHabilitarAguardarProcesso = QtGui.QAction(MainWindowDual)
        self.actionHabilitarAguardarProcesso.setObjectName("actionHabilitarAguardarProcesso")
        self.actionDesabilitarAguardarProcesso = QtGui.QAction(MainWindowDual)
        self.actionDesabilitarAguardarProcesso.setObjectName("actionDesabilitarAguardarProcesso")
        self.actionHabilitarEnterFinal = QtGui.QAction(MainWindowDual)
        self.actionHabilitarEnterFinal.setObjectName("actionHabilitarEnterFinal")
        self.actionDesabilitarEnterFinal = QtGui.QAction(MainWindowDual)
        self.actionDesabilitarEnterFinal.setObjectName("actionDesabilitarEnterFinal")
        self.actionPadraoGaveta = QtGui.QAction(MainWindowDual)
        self.actionPadraoGaveta.setObjectName("actionPadraoGaveta")
        self.actionAlteraPadraoGaveta = QtGui.QAction(MainWindowDual)
        self.actionAlteraPadraoGaveta.setObjectName("actionAlteraPadraoGaveta")
        self.actionHabilitarTermica = QtGui.QAction(MainWindowDual)
        self.actionHabilitarTermica.setObjectName("actionHabilitarTermica")
        self.actionDesabilitarTermica = QtGui.QAction(MainWindowDual)
        self.actionDesabilitarTermica.setObjectName("actionDesabilitarTermica")
        self.actionHabilitarCodePageAutomatico = QtGui.QAction(MainWindowDual)
        self.actionHabilitarCodePageAutomatico.setObjectName("actionHabilitarCodePageAutomatico")
        self.actionDesabilitarCodePageAutomatico = QtGui.QAction(MainWindowDual)
        self.actionDesabilitarCodePageAutomatico.setObjectName("actionDesabilitarCodePageAutomatico")
        self.actionHabilitarZeroCortado = QtGui.QAction(MainWindowDual)
        self.actionHabilitarZeroCortado.setObjectName("actionHabilitarZeroCortado")
        self.actionDesabilitarZeroCortado = QtGui.QAction(MainWindowDual)
        self.actionDesabilitarZeroCortado.setObjectName("actionDesabilitarZeroCortado")
        self.actionM_todo_rStatusImpressora_DUAL_DarumaFramework = QtGui.QAction(MainWindowDual)
        self.actionM_todo_rStatusImpressora_DUAL_DarumaFramework.setObjectName("actionM_todo_rStatusImpressora_DUAL_DarumaFramework")
        self.actionM_todo_rStatusDocumento_DUAL_DarumaFramework = QtGui.QAction(MainWindowDual)
        self.actionM_todo_rStatusDocumento_DUAL_DarumaFramework.setObjectName("actionM_todo_rStatusDocumento_DUAL_DarumaFramework")
        self.actionM_todo_rStatusGaveta_DUAL_DarumaFramework = QtGui.QAction(MainWindowDual)
        self.actionM_todo_rStatusGaveta_DUAL_DarumaFramework.setObjectName("actionM_todo_rStatusGaveta_DUAL_DarumaFramework")
        self.actionM_todo_rConsultaStatusImpressora_DUAL_DarumaFramework = QtGui.QAction(MainWindowDual)
        self.actionM_todo_rConsultaStatusImpressora_DUAL_DarumaFramework.setObjectName("actionM_todo_rConsultaStatusImpressora_DUAL_DarumaFramework")
        self.actionTeste_para_Looping_de_verica_o_de_Status = QtGui.QAction(MainWindowDual)
        self.actionTeste_para_Looping_de_verica_o_de_Status.setObjectName("actionTeste_para_Looping_de_verica_o_de_Status")
        self.actionTeste_para_Looping_de_verifica_ao_de_Status_de_Documento = QtGui.QAction(MainWindowDual)
        self.actionTeste_para_Looping_de_verifica_ao_de_Status_de_Documento.setObjectName("actionTeste_para_Looping_de_verifica_ao_de_Status_de_Documento")
        self.actionM_todo_iImprimirTexto_DUAL_DarumaFramework = QtGui.QAction(MainWindowDual)
        self.actionM_todo_iImprimirTexto_DUAL_DarumaFramework.setObjectName("actionM_todo_iImprimirTexto_DUAL_DarumaFramework")
        self.actionM_todo_iImprimirArquivo_DUAL_DarumaFramework = QtGui.QAction(MainWindowDual)
        self.actionM_todo_iImprimirArquivo_DUAL_DarumaFramework.setObjectName("actionM_todo_iImprimirArquivo_DUAL_DarumaFramework")
        self.actionM_todo_iAutenticarDocumento_DUAL_DarumaFramework = QtGui.QAction(MainWindowDual)
        self.actionM_todo_iAutenticarDocumento_DUAL_DarumaFramework.setObjectName("actionM_todo_iAutenticarDocumento_DUAL_DarumaFramework")
        self.actionM_todo_iAcionarGaveta_DUAL_DarumaFramework = QtGui.QAction(MainWindowDual)
        self.actionM_todo_iAcionarGaveta_DUAL_DarumaFramework.setObjectName("actionM_todo_iAcionarGaveta_DUAL_DarumaFramework")
        self.actionM_todo_iEnviarBMP_DUAL_DarumaFramework = QtGui.QAction(MainWindowDual)
        self.actionM_todo_iEnviarBMP_DUAL_DarumaFramework.setObjectName("actionM_todo_iEnviarBMP_DUAL_DarumaFramework")
        self.actionExemplo_1_Buffer = QtGui.QAction(MainWindowDual)
        self.actionExemplo_1_Buffer.setObjectName("actionExemplo_1_Buffer")
        self.actionExemplo_2_Tabula_o = QtGui.QAction(MainWindowDual)
        self.actionExemplo_2_Tabula_o.setObjectName("actionExemplo_2_Tabula_o")
        self.actionExemplo_3_Linha_a_Linha = QtGui.QAction(MainWindowDual)
        self.actionExemplo_3_Linha_a_Linha.setObjectName("actionExemplo_3_Linha_a_Linha")
        self.actionExemplo_4_Formulario = QtGui.QAction(MainWindowDual)
        self.actionExemplo_4_Formulario.setObjectName("actionExemplo_4_Formulario")
        self.actionExemplo_1_Buffer_2 = QtGui.QAction(MainWindowDual)
        self.actionExemplo_1_Buffer_2.setObjectName("actionExemplo_1_Buffer_2")
        self.actionExemplo_2_Tabula_ao = QtGui.QAction(MainWindowDual)
        self.actionExemplo_2_Tabula_ao.setObjectName("actionExemplo_2_Tabula_ao")
        self.actionExemplo_3_Linha_a_Linha_2 = QtGui.QAction(MainWindowDual)
        self.actionExemplo_3_Linha_a_Linha_2.setObjectName("actionExemplo_3_Linha_a_Linha_2")
        self.actionTeste_Completo_em_Buffer = QtGui.QAction(MainWindowDual)
        self.actionTeste_Completo_em_Buffer.setObjectName("actionTeste_Completo_em_Buffer")
        self.actionTeste_Completo_Linha_a_Linha = QtGui.QAction(MainWindowDual)
        self.actionTeste_Completo_Linha_a_Linha.setObjectName("actionTeste_Completo_Linha_a_Linha")
        self.menuM_todos_para_DarumaFramework.addAction(self.actionM_todo_eDefinirProduto_Daruma)
        self.menuM_todos_para_DarumaFramework.addAction(self.actionM_todo_regRetornaValorChave_DarumaFramework)
        self.menuM_todo_regAguardarProcesso_DUAL_DarumaFramework.addAction(self.actionHabilitarAguardarProcesso)
        self.menuM_todo_regAguardarProcesso_DUAL_DarumaFramework.addAction(self.actionDesabilitarAguardarProcesso)
        self.menuM_todo_regEnterFinal_DUAL_DarumaFramework.addAction(self.actionHabilitarEnterFinal)
        self.menuM_todo_regEnterFinal_DUAL_DarumaFramework.addAction(self.actionDesabilitarEnterFinal)
        self.menuM_todo_regModoGaveta_DUAL_DarumaFramework.addAction(self.actionPadraoGaveta)
        self.menuM_todo_regModoGaveta_DUAL_DarumaFramework.addAction(self.actionAlteraPadraoGaveta)
        self.menuM_todo_regTermica_DUAL_DarumaFramework.addAction(self.actionHabilitarTermica)
        self.menuM_todo_regTermica_DUAL_DarumaFramework.addAction(self.actionDesabilitarTermica)
        self.menuM_todo_regCodePageAutomatico_DUAL_DarumaFramework.addAction(self.actionHabilitarCodePageAutomatico)
        self.menuM_todo_regCodePageAutomatico_DUAL_DarumaFramework.addAction(self.actionDesabilitarCodePageAutomatico)
        self.menuM_todo_regZeroCortado_DUAL_DarumaFramework.addAction(self.actionHabilitarZeroCortado)
        self.menuM_todo_regZeroCortado_DUAL_DarumaFramework.addAction(self.actionDesabilitarZeroCortado)
        self.menuM_todos_para_Registro_Registry.addAction(self.menuM_todo_regAguardarProcesso_DUAL_DarumaFramework.menuAction())
        self.menuM_todos_para_Registro_Registry.addAction(self.menuM_todo_regEnterFinal_DUAL_DarumaFramework.menuAction())
        self.menuM_todos_para_Registro_Registry.addAction(self.actionM_todo_regLinhasGuilhotina_DUAL_DarumaFramework)
        self.menuM_todos_para_Registro_Registry.addAction(self.menuM_todo_regModoGaveta_DUAL_DarumaFramework.menuAction())
        self.menuM_todos_para_Registro_Registry.addAction(self.actionM_todo_regPortaComunicacao_DUAL_DarumaFramework)
        self.menuM_todos_para_Registro_Registry.addAction(self.actionM_todo_regTabulacao_DUAL_DarumaFramework)
        self.menuM_todos_para_Registro_Registry.addAction(self.menuM_todo_regTermica_DUAL_DarumaFramework.menuAction())
        self.menuM_todos_para_Registro_Registry.addAction(self.actionM_todo_regVelocidade_DUAL_DarumaFramework)
        self.menuM_todos_para_Registro_Registry.addAction(self.menuM_todo_regCodePageAutomatico_DUAL_DarumaFramework.menuAction())
        self.menuM_todos_para_Registro_Registry.addAction(self.menuM_todo_regZeroCortado_DUAL_DarumaFramework.menuAction())
        self.menuMenu_para_Testes.addAction(self.actionTeste_para_Looping_de_verica_o_de_Status)
        self.menuMenu_para_Testes.addAction(self.actionTeste_para_Looping_de_verifica_ao_de_Status_de_Documento)
        self.menuM_todos_para_Status_e_Testes.addAction(self.actionM_todo_rStatusImpressora_DUAL_DarumaFramework)
        self.menuM_todos_para_Status_e_Testes.addAction(self.actionM_todo_rStatusDocumento_DUAL_DarumaFramework)
        self.menuM_todos_para_Status_e_Testes.addAction(self.actionM_todo_rStatusGaveta_DUAL_DarumaFramework)
        self.menuM_todos_para_Status_e_Testes.addAction(self.actionM_todo_rConsultaStatusImpressora_DUAL_DarumaFramework)
        self.menuM_todos_para_Status_e_Testes.addAction(self.menuMenu_para_Testes.menuAction())
        self.menuM_todos_para_Autentica_ao_e_Impress_o.addAction(self.actionM_todo_iImprimirTexto_DUAL_DarumaFramework)
        self.menuM_todos_para_Autentica_ao_e_Impress_o.addAction(self.actionM_todo_iImprimirArquivo_DUAL_DarumaFramework)
        self.menuM_todos_para_Autentica_ao_e_Impress_o.addAction(self.actionM_todo_iAutenticarDocumento_DUAL_DarumaFramework)
        self.menuM_todos_para_Autentica_ao_e_Impress_o.addAction(self.actionM_todo_iAcionarGaveta_DUAL_DarumaFramework)
        self.menuM_todos_para_Autentica_ao_e_Impress_o.addAction(self.actionM_todo_iEnviarBMP_DUAL_DarumaFramework)
        self.menuExemplos.addAction(self.actionExemplo_1_Buffer)
        self.menuExemplos.addAction(self.actionExemplo_2_Tabula_o)
        self.menuExemplos.addAction(self.actionExemplo_3_Linha_a_Linha)
        self.menuExemplos.addAction(self.actionExemplo_4_Formulario)
        self.menuBobina_35_Colunas.addAction(self.actionExemplo_1_Buffer_2)
        self.menuBobina_35_Colunas.addAction(self.actionExemplo_2_Tabula_ao)
        self.menuBobina_35_Colunas.addAction(self.actionExemplo_3_Linha_a_Linha_2)
        self.menuBobina_35_Colunas.addAction(self.actionTeste_Completo_em_Buffer)
        self.menuBobina_35_Colunas.addAction(self.actionTeste_Completo_Linha_a_Linha)
        self.menubar.addAction(self.menuM_todos_para_DarumaFramework.menuAction())
        self.menubar.addAction(self.menuM_todos_para_Registro_Registry.menuAction())
        self.menubar.addAction(self.menuM_todos_para_Status_e_Testes.menuAction())
        self.menubar.addAction(self.menuM_todos_para_Autentica_ao_e_Impress_o.menuAction())
        self.menubar.addAction(self.menuExemplos.menuAction())
        self.menubar.addAction(self.menuBobina_35_Colunas.menuAction())

        self.retranslateUi(MainWindowDual)
        QtCore.QMetaObject.connectSlotsByName(MainWindowDual)

    def retranslateUi(self, MainWindowDual):
        MainWindowDual.setWindowTitle(QtGui.QApplication.translate("MainWindowDual", "DarumaFrameWork - Módulo DUAL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindowDual", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Dúvidas? Ligue: 0800 77 0332 0</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindowDual", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Impressora Não Fiscal</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Verdana\'; font-size:12pt; font-weight:600;\">DLL: DarumaFramework.dll</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindowDual", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/Recursos/Imagens/logo_daruma_developers.png\" /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonEncerrar.setText(QtGui.QApplication.translate("MainWindowDual", "Fechar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuM_todos_para_DarumaFramework.setTitle(QtGui.QApplication.translate("MainWindowDual", "Métodos para DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.menuM_todos_para_Registro_Registry.setTitle(QtGui.QApplication.translate("MainWindowDual", "Métodos para Registro(Registry)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuM_todo_regAguardarProcesso_DUAL_DarumaFramework.setTitle(QtGui.QApplication.translate("MainWindowDual", "Método regAguardarProcesso_DUAL_DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.menuM_todo_regEnterFinal_DUAL_DarumaFramework.setTitle(QtGui.QApplication.translate("MainWindowDual", "Método regEnterFinal_DUAL_DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.menuM_todo_regModoGaveta_DUAL_DarumaFramework.setTitle(QtGui.QApplication.translate("MainWindowDual", "Método regModoGaveta_DUAL_DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.menuM_todo_regTermica_DUAL_DarumaFramework.setTitle(QtGui.QApplication.translate("MainWindowDual", "Método regTermica_DUAL_DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.menuM_todo_regCodePageAutomatico_DUAL_DarumaFramework.setTitle(QtGui.QApplication.translate("MainWindowDual", "Método regCodePageAutomatico_DUAL_DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.menuM_todo_regZeroCortado_DUAL_DarumaFramework.setTitle(QtGui.QApplication.translate("MainWindowDual", "Método regZeroCortado_DUAL_DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.menuM_todos_para_Status_e_Testes.setTitle(QtGui.QApplication.translate("MainWindowDual", "Métodos para Status e Testes", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu_para_Testes.setTitle(QtGui.QApplication.translate("MainWindowDual", "Menu para Testes", None, QtGui.QApplication.UnicodeUTF8))
        self.menuM_todos_para_Autentica_ao_e_Impress_o.setTitle(QtGui.QApplication.translate("MainWindowDual", "Métodos para Autenticaçao e Impressão", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExemplos.setTitle(QtGui.QApplication.translate("MainWindowDual", "Exemplos", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBobina_35_Colunas.setTitle(QtGui.QApplication.translate("MainWindowDual", "Bobina 35 Colunas", None, QtGui.QApplication.UnicodeUTF8))
        self.actionM_todo_eDefinirProduto_Daruma.setText(QtGui.QApplication.translate("MainWindowDual", "Método eDefinirProduto_Daruma", None, QtGui.QApplication.UnicodeUTF8))
        self.actionM_todo_regRetornaValorChave_DarumaFramework.setText(QtGui.QApplication.translate("MainWindowDual", "Método regRetornaValorChave_DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.actionM_todo_regLinhasGuilhotina_DUAL_DarumaFramework.setText(QtGui.QApplication.translate("MainWindowDual", "Método regLinhasGuilhotina_DUAL_DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.actionM_todo_regPortaComunicacao_DUAL_DarumaFramework.setText(QtGui.QApplication.translate("MainWindowDual", "Método regPortaComunicacao_DUAL_DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.actionM_todo_regTabulacao_DUAL_DarumaFramework.setText(QtGui.QApplication.translate("MainWindowDual", "Método regTabulacao_DUAL_DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.actionM_todo_regVelocidade_DUAL_DarumaFramework.setText(QtGui.QApplication.translate("MainWindowDual", "Método regVelocidade_DUAL_DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.action1_Habilitar.setText(QtGui.QApplication.translate("MainWindowDual", "1 - Habilitar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHabilitarAguardarProcesso.setText(QtGui.QApplication.translate("MainWindowDual", "1 - Habilitar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDesabilitarAguardarProcesso.setText(QtGui.QApplication.translate("MainWindowDual", "0 - Desabilitar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHabilitarEnterFinal.setText(QtGui.QApplication.translate("MainWindowDual", "1 - Habilitar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDesabilitarEnterFinal.setText(QtGui.QApplication.translate("MainWindowDual", "0 - Desabilitar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPadraoGaveta.setText(QtGui.QApplication.translate("MainWindowDual", "0 - Padrão", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlteraPadraoGaveta.setText(QtGui.QApplication.translate("MainWindowDual", "1 - Altera Padrão", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHabilitarTermica.setText(QtGui.QApplication.translate("MainWindowDual", "1 - Habilitar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDesabilitarTermica.setText(QtGui.QApplication.translate("MainWindowDual", "0 - Desabilitar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHabilitarCodePageAutomatico.setText(QtGui.QApplication.translate("MainWindowDual", "1 - Habilitar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDesabilitarCodePageAutomatico.setText(QtGui.QApplication.translate("MainWindowDual", "0 - Desabilitar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHabilitarZeroCortado.setText(QtGui.QApplication.translate("MainWindowDual", "1 - Habilitar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDesabilitarZeroCortado.setText(QtGui.QApplication.translate("MainWindowDual", "0 - Desabilitar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionM_todo_rStatusImpressora_DUAL_DarumaFramework.setText(QtGui.QApplication.translate("MainWindowDual", "Método rStatusImpressora_DUAL_DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.actionM_todo_rStatusDocumento_DUAL_DarumaFramework.setText(QtGui.QApplication.translate("MainWindowDual", "Método rStatusDocumento_DUAL_DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.actionM_todo_rStatusGaveta_DUAL_DarumaFramework.setText(QtGui.QApplication.translate("MainWindowDual", "Método rStatusGaveta_DUAL_DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.actionM_todo_rConsultaStatusImpressora_DUAL_DarumaFramework.setText(QtGui.QApplication.translate("MainWindowDual", "Método rConsultaStatusImpressora_DUAL_DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTeste_para_Looping_de_verica_o_de_Status.setText(QtGui.QApplication.translate("MainWindowDual", "Teste para Looping de verificação de Status", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTeste_para_Looping_de_verifica_ao_de_Status_de_Documento.setText(QtGui.QApplication.translate("MainWindowDual", "Teste para Looping de verificaçao de Status de Documento", None, QtGui.QApplication.UnicodeUTF8))
        self.actionM_todo_iImprimirTexto_DUAL_DarumaFramework.setText(QtGui.QApplication.translate("MainWindowDual", "Método iImprimirTexto_DUAL_DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.actionM_todo_iImprimirArquivo_DUAL_DarumaFramework.setText(QtGui.QApplication.translate("MainWindowDual", "Método iImprimirArquivo_DUAL_DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.actionM_todo_iAutenticarDocumento_DUAL_DarumaFramework.setText(QtGui.QApplication.translate("MainWindowDual", "Método iAutenticarDocumento_DUAL_DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.actionM_todo_iAcionarGaveta_DUAL_DarumaFramework.setText(QtGui.QApplication.translate("MainWindowDual", "Método iAcionarGaveta_DUAL_DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.actionM_todo_iEnviarBMP_DUAL_DarumaFramework.setText(QtGui.QApplication.translate("MainWindowDual", "Método iEnviarBMP_DUAL_DarumaFramework", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExemplo_1_Buffer.setText(QtGui.QApplication.translate("MainWindowDual", "Exemplo 1 (Buffer)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExemplo_2_Tabula_o.setText(QtGui.QApplication.translate("MainWindowDual", "Exemplo 2 (Tabulação)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExemplo_3_Linha_a_Linha.setText(QtGui.QApplication.translate("MainWindowDual", "Exemplo 3 (Linha-a-Linha)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExemplo_4_Formulario.setText(QtGui.QApplication.translate("MainWindowDual", "Exemplo 4 (Formulário)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExemplo_1_Buffer_2.setText(QtGui.QApplication.translate("MainWindowDual", "Exemplo 1 (Buffer)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExemplo_2_Tabula_ao.setText(QtGui.QApplication.translate("MainWindowDual", "Exemplo 2 (Tabulação)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExemplo_3_Linha_a_Linha_2.setText(QtGui.QApplication.translate("MainWindowDual", "Exemplo 3 (Linha-a-Linha)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTeste_Completo_em_Buffer.setText(QtGui.QApplication.translate("MainWindowDual", "Teste Completo em Buffer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTeste_Completo_Linha_a_Linha.setText(QtGui.QApplication.translate("MainWindowDual", "Teste Completo Linha-a-Linha", None, QtGui.QApplication.UnicodeUTF8))

